#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOPE_ROOT="$PROJECT_ROOT/hope"

DEFAULT_SOURCE_HOPE="$HOPE_ROOT/sft/llava_rl_seqrec_rule.hope"
DEFAULT_SOURCE_IGNORE="$HOPE_ROOT/sft/.hopeignore"

SOURCE_HOPE="${SOURCE_HOPE:-$DEFAULT_SOURCE_HOPE}"
SOURCE_IGNORE="${SOURCE_IGNORE:-$DEFAULT_SOURCE_IGNORE}"
DEFAULT_TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
SYNC_ROOT_HOPEIGNORE="${SYNC_ROOT_HOPEIGNORE:-true}"
REQUIRED_IGNORE_PATTERNS=(
  "wandb"
  "wandb/**"
  "wandb_snap/"
  "wandb_snap/**"
  "wandb/"
  "tf_events/"
  "tf_events/**"
  "docs/"
  "docs/**"
  "index_train_runs/"
  "index_train_runs/**"
  "results/"
  "results/**"
  "log/"
  "flash_attn*"
  "flash_attn*/**"
  "artifacts/"
  "artifacts/*"
  ".cache/"
  ".cache/*"
)

is_truthy() {
  case "${1,,}" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

append_missing_patterns() {
  local target_file="$1"
  if [[ ! -f "$target_file" ]]; then
    : > "$target_file"
  fi
  for pattern in "${REQUIRED_IGNORE_PATTERNS[@]}"; do
    if ! grep -Fxq "$pattern" "$target_file"; then
      echo "$pattern" >> "$target_file"
    fi
  done
}

usage() {
  cat <<'USAGE'
Usage:
  bash scripts/hope/create_sft_job_template.sh <job_prefix> <worker_script_path> [timestamp]

Behavior:
  1) Build run name: <job_prefix>_<timestamp>.
  2) Create hope/<job_prefix>_<timestamp>/ directory.
  3) Run: hope init ml-easy-job <job_prefix>_<timestamp>
  4) Copy SFT config from SOURCE_HOPE into generated .hope file.
  5) Set worker.script = bash <worker_script_path>
  6) Copy SOURCE_IGNORE to .hopeignore (if present).

Arguments:
  job_prefix          Prefix for job/run name.
  worker_script_path  Path to the script used in worker.script.
  timestamp           Optional timestamp. Default: current time.

Examples:
  bash scripts/hope/create_sft_job_template.sh llava_sft scripts/finetune/train_text.sh
  bash scripts/hope/create_sft_job_template.sh llava_sft /abs/path/run.sh 20260213_210000

Environment:
  SOURCE_HOPE         Source config file. Default: hope/sft/llava_rl_seqrec_rule.hope
  SOURCE_IGNORE       Source ignore file. Default: hope/sft/.hopeignore
  SYNC_ROOT_HOPEIGNORE
                      Whether to sync ignore patterns to <repo>/.hopeignore.
                      Default: true
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ $# -lt 2 || $# -gt 3 ]]; then
  usage
  exit 1
fi

JOB_PREFIX_RAW="$1"
WORKER_SCRIPT_PATH="$2"
TIMESTAMP="${3:-$DEFAULT_TIMESTAMP}"

JOB_PREFIX="${JOB_PREFIX_RAW// /-}"
if [[ -z "$JOB_PREFIX" ]]; then
  echo "Error: job_prefix is empty after normalization." >&2
  exit 1
fi

RUN_NAME="${JOB_PREFIX}_${TIMESTAMP}"
TARGET_DIR="$HOPE_ROOT/$RUN_NAME"
WORKER_SCRIPT_VALUE="bash ${WORKER_SCRIPT_PATH}"

if [[ ! "$TIMESTAMP" =~ ^[0-9]{8}_[0-9]{6}$ ]]; then
  echo "Warning: timestamp format is not YYYYmmdd_HHMMSS: $TIMESTAMP" >&2
fi

if [[ ! -d "$HOPE_ROOT" ]]; then
  echo "Error: hope directory not found: $HOPE_ROOT" >&2
  exit 1
fi

if [[ ! -f "$SOURCE_HOPE" ]]; then
  echo "Error: SOURCE_HOPE not found: $SOURCE_HOPE" >&2
  exit 1
fi

if ! command -v hope >/dev/null 2>&1; then
  echo "Error: 'hope' command not found in PATH." >&2
  exit 1
fi

if [[ -e "$TARGET_DIR" ]]; then
  echo "Error: target directory already exists: $TARGET_DIR" >&2
  echo "Hint: use another timestamp." >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"
cd "$TARGET_DIR"

echo "Initializing hope template in: $TARGET_DIR"
hope init ml-easy-job "$RUN_NAME"

shopt -s nullglob
hope_files=("$TARGET_DIR"/*.hope)
shopt -u nullglob

if [[ ${#hope_files[@]} -eq 0 ]]; then
  echo "Error: no .hope file generated by hope init in $TARGET_DIR" >&2
  exit 1
fi

target_hope_file="${hope_files[0]}"

tmp_file="$(mktemp)"
awk -v worker_script_value="$WORKER_SCRIPT_VALUE" '
  BEGIN { in_roles=0 }
  /^\[/ {
    in_roles = ($0 == "[roles]")
  }
  in_roles && $0 ~ /^worker\.script[[:space:]]*=/ {
    $0 = "worker.script = " worker_script_value
    replaced = 1
  }
  { print }
  END {
    if (!replaced) exit 2
  }
' "$SOURCE_HOPE" > "$tmp_file" || {
  rm -f "$tmp_file"
  echo "Error: failed to set worker.script in SOURCE_HOPE: $SOURCE_HOPE" >&2
  exit 1
}

mv "$tmp_file" "$target_hope_file"

if [[ -f "$SOURCE_IGNORE" ]]; then
  cp "$SOURCE_IGNORE" "$TARGET_DIR/.hopeignore"
else
  : > "$TARGET_DIR/.hopeignore"
fi

append_missing_patterns "$TARGET_DIR/.hopeignore"

if [[ -f "$TARGET_DIR/.hopeignore" ]]; then
  echo "Generated .hopeignore: $TARGET_DIR/.hopeignore"
fi

if is_truthy "$SYNC_ROOT_HOPEIGNORE"; then
  ROOT_IGNORE_FILE="$PROJECT_ROOT/.hopeignore"
  append_missing_patterns "$ROOT_IGNORE_FILE"
  echo "Synced root .hopeignore: $ROOT_IGNORE_FILE"
fi

submit_script="$TARGET_DIR/submit.sh"
target_hope_name="$(basename "$target_hope_file")"
cat > "$submit_script" <<EOF
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
hope run "$target_hope_name"
EOF
chmod +x "$submit_script"

echo "Done."
echo "Run name: $RUN_NAME"
echo "Created directory: $TARGET_DIR"
echo "Generated hope file: $target_hope_file"
echo "Set worker.script = $WORKER_SCRIPT_VALUE"
echo "Submit script: $submit_script"
echo "Recommended submit command: (cd \"$TARGET_DIR\" && hope run \"$(basename "$target_hope_file")\")"
