#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$PROJECT_ROOT" || exit 1

# IAG: Instruments + Arts + Games
: "${ROOT_DIR:=/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian}"
: "${DATA_ROOT:=${ROOT_DIR}/data}"
: "${MODEL_NAME:=qwen3-embedding-4B}"
: "${USE_MULTI_DATASETS:=true}"
: "${DATASETS:=Instruments Arts Games}"

# Required: checkpoint generated by index training.
: "${CKPT_PATH:=}"
if [[ -z "$CKPT_PATH" ]]; then
  echo "Error: CKPT_PATH is empty."
  echo "Example: CKPT_PATH=./index_train_runs/Instruments-Arts-Games/index/qwen3-embedding-4B/run_tag/run_time/best_collision_model.pth bash scripts/index/Instruments-Arts-Games-qwen3-embedding-4B-rq3_cb512-512-512_sk0.0-0.0-0.003/generate.sh"
  exit 1
fi

export ROOT_DIR DATA_ROOT MODEL_NAME USE_MULTI_DATASETS DATASETS CKPT_PATH

# Optional overrides (examples):
#   BATCH_SIZE=64 DEVICE=cuda:0 OUTPUT_SUFFIX=.index_custom.json
bash scripts/index/base/generate.sh
